//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace GJHF.Data.Model.PLC
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class ONPE_SJEntitiesModel : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“ONPE_SJEntitiesModel”部分中的连接字符串初始化新 ONPE_SJEntitiesModel 对象。
        /// </summary>
        public ONPE_SJEntitiesModel() : base("name=ONPE_SJEntitiesModel", "ONPE_SJEntitiesModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ONPE_SJEntitiesModel 对象。
        /// </summary>
        public ONPE_SJEntitiesModel(string connectionString) : base(connectionString, "ONPE_SJEntitiesModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 ONPE_SJEntitiesModel 对象。
        /// </summary>
        public ONPE_SJEntitiesModel(EntityConnection connection) : base(connection, "ONPE_SJEntitiesModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tZPlcPointDiZhi> tZPlcPointDiZhi
        {
            get
            {
                if ((_tZPlcPointDiZhi == null))
                {
                    _tZPlcPointDiZhi = base.CreateObjectSet<tZPlcPointDiZhi>("tZPlcPointDiZhi");
                }
                return _tZPlcPointDiZhi;
            }
        }
        private ObjectSet<tZPlcPointDiZhi> _tZPlcPointDiZhi;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 tZPlcPointDiZhi EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotZPlcPointDiZhi(tZPlcPointDiZhi tZPlcPointDiZhi)
        {
            base.AddObject("tZPlcPointDiZhi", tZPlcPointDiZhi);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ONPE_SJModel", Name="tZPlcPointDiZhi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tZPlcPointDiZhi : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tZPlcPointDiZhi 对象。
        /// </summary>
        /// <param name="dIntDataID">dIntDataID 属性的初始值。</param>
        public static tZPlcPointDiZhi CreatetZPlcPointDiZhi(global::System.Int64 dIntDataID)
        {
            tZPlcPointDiZhi tZPlcPointDiZhi = new tZPlcPointDiZhi();
            tZPlcPointDiZhi.dIntDataID = dIntDataID;
            return tZPlcPointDiZhi;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 dIntDataID
        {
            get
            {
                return _dIntDataID;
            }
            set
            {
                if (_dIntDataID != value)
                {
                    OndIntDataIDChanging(value);
                    ReportPropertyChanging("dIntDataID");
                    _dIntDataID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("dIntDataID");
                    OndIntDataIDChanged();
                }
            }
        }
        private global::System.Int64 _dIntDataID;
        partial void OndIntDataIDChanging(global::System.Int64 value);
        partial void OndIntDataIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dVchAdressName
        {
            get
            {
                return _dVchAdressName;
            }
            set
            {
                OndVchAdressNameChanging(value);
                ReportPropertyChanging("dVchAdressName");
                _dVchAdressName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dVchAdressName");
                OndVchAdressNameChanged();
            }
        }
        private global::System.String _dVchAdressName;
        partial void OndVchAdressNameChanging(global::System.String value);
        partial void OndVchAdressNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dVchAddress
        {
            get
            {
                return _dVchAddress;
            }
            set
            {
                OndVchAddressChanging(value);
                ReportPropertyChanging("dVchAddress");
                _dVchAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dVchAddress");
                OndVchAddressChanged();
            }
        }
        private global::System.String _dVchAddress;
        partial void OndVchAddressChanging(global::System.String value);
        partial void OndVchAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dVchAllAdress
        {
            get
            {
                return _dVchAllAdress;
            }
            set
            {
                OndVchAllAdressChanging(value);
                ReportPropertyChanging("dVchAllAdress");
                _dVchAllAdress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dVchAllAdress");
                OndVchAllAdressChanged();
            }
        }
        private global::System.String _dVchAllAdress;
        partial void OndVchAllAdressChanging(global::System.String value);
        partial void OndVchAllAdressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dVchDescription
        {
            get
            {
                return _dVchDescription;
            }
            set
            {
                OndVchDescriptionChanging(value);
                ReportPropertyChanging("dVchDescription");
                _dVchDescription = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dVchDescription");
                OndVchDescriptionChanged();
            }
        }
        private global::System.String _dVchDescription;
        partial void OndVchDescriptionChanging(global::System.String value);
        partial void OndVchDescriptionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntDataType
        {
            get
            {
                return _dIntDataType;
            }
            set
            {
                OndIntDataTypeChanging(value);
                ReportPropertyChanging("dIntDataType");
                _dIntDataType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntDataType");
                OndIntDataTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntDataType;
        partial void OndIntDataTypeChanging(Nullable<global::System.Int32> value);
        partial void OndIntDataTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> dFltBeishu
        {
            get
            {
                return _dFltBeishu;
            }
            set
            {
                OndFltBeishuChanging(value);
                ReportPropertyChanging("dFltBeishu");
                _dFltBeishu = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dFltBeishu");
                OndFltBeishuChanged();
            }
        }
        private Nullable<global::System.Double> _dFltBeishu;
        partial void OndFltBeishuChanging(Nullable<global::System.Double> value);
        partial void OndFltBeishuChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> dFltMoniMax
        {
            get
            {
                return _dFltMoniMax;
            }
            set
            {
                OndFltMoniMaxChanging(value);
                ReportPropertyChanging("dFltMoniMax");
                _dFltMoniMax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dFltMoniMax");
                OndFltMoniMaxChanged();
            }
        }
        private Nullable<global::System.Double> _dFltMoniMax;
        partial void OndFltMoniMaxChanging(Nullable<global::System.Double> value);
        partial void OndFltMoniMaxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> dFltMoniMin
        {
            get
            {
                return _dFltMoniMin;
            }
            set
            {
                OndFltMoniMinChanging(value);
                ReportPropertyChanging("dFltMoniMin");
                _dFltMoniMin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dFltMoniMin");
                OndFltMoniMinChanged();
            }
        }
        private Nullable<global::System.Double> _dFltMoniMin;
        partial void OndFltMoniMinChanging(Nullable<global::System.Double> value);
        partial void OndFltMoniMinChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> dFltSjMax
        {
            get
            {
                return _dFltSjMax;
            }
            set
            {
                OndFltSjMaxChanging(value);
                ReportPropertyChanging("dFltSjMax");
                _dFltSjMax = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dFltSjMax");
                OndFltSjMaxChanged();
            }
        }
        private Nullable<global::System.Double> _dFltSjMax;
        partial void OndFltSjMaxChanging(Nullable<global::System.Double> value);
        partial void OndFltSjMaxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> dFltSjMin
        {
            get
            {
                return _dFltSjMin;
            }
            set
            {
                OndFltSjMinChanging(value);
                ReportPropertyChanging("dFltSjMin");
                _dFltSjMin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dFltSjMin");
                OndFltSjMinChanged();
            }
        }
        private Nullable<global::System.Double> _dFltSjMin;
        partial void OndFltSjMinChanging(Nullable<global::System.Double> value);
        partial void OndFltSjMinChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dVchDanwei
        {
            get
            {
                return _dVchDanwei;
            }
            set
            {
                OndVchDanweiChanging(value);
                ReportPropertyChanging("dVchDanwei");
                _dVchDanwei = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dVchDanwei");
                OndVchDanweiChanged();
            }
        }
        private global::System.String _dVchDanwei;
        partial void OndVchDanweiChanging(global::System.String value);
        partial void OndVchDanweiChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntGongType
        {
            get
            {
                return _dIntGongType;
            }
            set
            {
                OndIntGongTypeChanging(value);
                ReportPropertyChanging("dIntGongType");
                _dIntGongType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntGongType");
                OndIntGongTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntGongType;
        partial void OndIntGongTypeChanging(Nullable<global::System.Int32> value);
        partial void OndIntGongTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntNengYuanType
        {
            get
            {
                return _dIntNengYuanType;
            }
            set
            {
                OndIntNengYuanTypeChanging(value);
                ReportPropertyChanging("dIntNengYuanType");
                _dIntNengYuanType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntNengYuanType");
                OndIntNengYuanTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntNengYuanType;
        partial void OndIntNengYuanTypeChanging(Nullable<global::System.Int32> value);
        partial void OndIntNengYuanTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntPLCXitong
        {
            get
            {
                return _dIntPLCXitong;
            }
            set
            {
                OndIntPLCXitongChanging(value);
                ReportPropertyChanging("dIntPLCXitong");
                _dIntPLCXitong = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntPLCXitong");
                OndIntPLCXitongChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntPLCXitong;
        partial void OndIntPLCXitongChanging(Nullable<global::System.Int32> value);
        partial void OndIntPLCXitongChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dVchDataType
        {
            get
            {
                return _dVchDataType;
            }
            set
            {
                OndVchDataTypeChanging(value);
                ReportPropertyChanging("dVchDataType");
                _dVchDataType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dVchDataType");
                OndVchDataTypeChanged();
            }
        }
        private global::System.String _dVchDataType;
        partial void OndVchDataTypeChanging(global::System.String value);
        partial void OndVchDataTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntZongGZ
        {
            get
            {
                return _dIntZongGZ;
            }
            set
            {
                OndIntZongGZChanging(value);
                ReportPropertyChanging("dIntZongGZ");
                _dIntZongGZ = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntZongGZ");
                OndIntZongGZChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntZongGZ;
        partial void OndIntZongGZChanging(Nullable<global::System.Int32> value);
        partial void OndIntZongGZChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dVchSheBei1
        {
            get
            {
                return _dVchSheBei1;
            }
            set
            {
                OndVchSheBei1Changing(value);
                ReportPropertyChanging("dVchSheBei1");
                _dVchSheBei1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dVchSheBei1");
                OndVchSheBei1Changed();
            }
        }
        private global::System.String _dVchSheBei1;
        partial void OndVchSheBei1Changing(global::System.String value);
        partial void OndVchSheBei1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dVchSheBei2
        {
            get
            {
                return _dVchSheBei2;
            }
            set
            {
                OndVchSheBei2Changing(value);
                ReportPropertyChanging("dVchSheBei2");
                _dVchSheBei2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dVchSheBei2");
                OndVchSheBei2Changed();
            }
        }
        private global::System.String _dVchSheBei2;
        partial void OndVchSheBei2Changing(global::System.String value);
        partial void OndVchSheBei2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dVchNeiBuBL1
        {
            get
            {
                return _dVchNeiBuBL1;
            }
            set
            {
                OndVchNeiBuBL1Changing(value);
                ReportPropertyChanging("dVchNeiBuBL1");
                _dVchNeiBuBL1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dVchNeiBuBL1");
                OndVchNeiBuBL1Changed();
            }
        }
        private global::System.String _dVchNeiBuBL1;
        partial void OndVchNeiBuBL1Changing(global::System.String value);
        partial void OndVchNeiBuBL1Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dVchNeiBuBL2
        {
            get
            {
                return _dVchNeiBuBL2;
            }
            set
            {
                OndVchNeiBuBL2Changing(value);
                ReportPropertyChanging("dVchNeiBuBL2");
                _dVchNeiBuBL2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dVchNeiBuBL2");
                OndVchNeiBuBL2Changed();
            }
        }
        private global::System.String _dVchNeiBuBL2;
        partial void OndVchNeiBuBL2Changing(global::System.String value);
        partial void OndVchNeiBuBL2Changed();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntIOType
        {
            get
            {
                return _dIntIOType;
            }
            set
            {
                OndIntIOTypeChanging(value);
                ReportPropertyChanging("dIntIOType");
                _dIntIOType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntIOType");
                OndIntIOTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntIOType;
        partial void OndIntIOTypeChanging(Nullable<global::System.Int32> value);
        partial void OndIntIOTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntPLCID
        {
            get
            {
                return _dIntPLCID;
            }
            set
            {
                OndIntPLCIDChanging(value);
                ReportPropertyChanging("dIntPLCID");
                _dIntPLCID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntPLCID");
                OndIntPLCIDChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntPLCID;
        partial void OndIntPLCIDChanging(Nullable<global::System.Int32> value);
        partial void OndIntPLCIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntGzOrQd
        {
            get
            {
                return _dIntGzOrQd;
            }
            set
            {
                OndIntGzOrQdChanging(value);
                ReportPropertyChanging("dIntGzOrQd");
                _dIntGzOrQd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntGzOrQd");
                OndIntGzOrQdChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntGzOrQd;
        partial void OndIntGzOrQdChanging(Nullable<global::System.Int32> value);
        partial void OndIntGzOrQdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntPointType
        {
            get
            {
                return _dIntPointType;
            }
            set
            {
                OndIntPointTypeChanging(value);
                ReportPropertyChanging("dIntPointType");
                _dIntPointType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntPointType");
                OndIntPointTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntPointType;
        partial void OndIntPointTypeChanging(Nullable<global::System.Int32> value);
        partial void OndIntPointTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntAreaXitongID
        {
            get
            {
                return _dIntAreaXitongID;
            }
            set
            {
                OndIntAreaXitongIDChanging(value);
                ReportPropertyChanging("dIntAreaXitongID");
                _dIntAreaXitongID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntAreaXitongID");
                OndIntAreaXitongIDChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntAreaXitongID;
        partial void OndIntAreaXitongIDChanging(Nullable<global::System.Int32> value);
        partial void OndIntAreaXitongIDChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntShouJiPx
        {
            get
            {
                return _dIntShouJiPx;
            }
            set
            {
                OndIntShouJiPxChanging(value);
                ReportPropertyChanging("dIntShouJiPx");
                _dIntShouJiPx = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntShouJiPx");
                OndIntShouJiPxChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntShouJiPx;
        partial void OndIntShouJiPxChanging(Nullable<global::System.Int32> value);
        partial void OndIntShouJiPxChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> dIntJsBz
        {
            get
            {
                return _dIntJsBz;
            }
            set
            {
                OndIntJsBzChanging(value);
                ReportPropertyChanging("dIntJsBz");
                _dIntJsBz = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dIntJsBz");
                OndIntJsBzChanged();
            }
        }
        private Nullable<global::System.Int32> _dIntJsBz;
        partial void OndIntJsBzChanging(Nullable<global::System.Int32> value);
        partial void OndIntJsBzChanged();

        #endregion

    
    }

    #endregion

    
}
